-- @BLOCK
CREATE TABLE USERS(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    USERTYPE VARCHAR(255) NOT NULL,
    PASS VARCHAR(255) NOT NULL,
    FNAME TEXT
);
-- @BLOCK
INSERT INTO USERS (EMAIL, USERTYPE, PASS, FNAME)
VALUES ('abc@jymspace.com', 'admin')